import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/components/Providers'
import { Header } from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='min-h-full'>
      <body
        className={
          (inter.className, 'flex h-full flex-col bg-neutral-800 text-white')
        }
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
